version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: graphql-server
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/harmonize
      - "host.docker.internal:host-gateway"
    command: sh -c "npm run seed && npm start"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - "80:80"
    depends_on:
      - server
